
name: RPC Tests
on:
  push:
    branches: [main, release/**]
  pull_request:

jobs:
  test:
    name: test RPC
    runs-on: ubuntu-22.04
    services:
      rpc:
        image: stellar/quickstart:v423-testing
        ports:
          - 8000:8000
        env:
          ENABLE_LOGS: true
          ENABLE_SOROBAN_DIAGNOSTIC_EVENTS: true
          NETWORK: local
        options: >-
          --health-cmd "curl --no-progress-meter --fail-with-body -X POST \"http://localhost:8000/soroban/rpc\" -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":8675309,\"method\":\"getNetwork\"}' && curl --no-progress-meter \"http://localhost:8000/friendbot\" | grep '\"invalid_field\": \"addr\"'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 50
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: rustup update
    - run: cargo build
    - run: rustup target add wasm32-unknown-unknown
    - run: make build-test-wasms
    - run: SOROBAN_PORT=8000 cargo test --features it --package soroban-test --test it -- integration

